package garlicecies

import (
	"crypto/ecdh"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"testing"

	"gosuda.org/ivnp/cryptography"
	"gosuda.org/ivnp/foundation"
	"gosuda.org/ivnp/observability"
)

func ratchetPair(t testing.TB) (*RatchetManager, *RatchetManager, foundation.Hash, foundation.Hash, uint64) {
	return ratchetPairWithMetrics(t, nil)
}

func ratchetPairWithMetrics(t testing.TB, metrics *observability.Registry) (*RatchetManager, *RatchetManager, foundation.Hash, foundation.Hash, uint64) {
	t.Helper()
	a, err := foundation.GenerateLocalDestination()
	if err != nil {
		t.Fatal(err)
	}
	b, err := foundation.GenerateLocalDestination()
	if err != nil {
		t.Fatal(err)
	}
	aM, err := NewRatchetManager(a, RatchetConfig{TagLookahead: 4, Metrics: metrics})
	if err != nil {
		t.Fatal(err)
	}
	bM, err := NewRatchetManager(b, RatchetConfig{TagLookahead: 4, Metrics: metrics})
	if err != nil {
		t.Fatal(err)
	}
	return aM, bM, a.Hash(), b.Hash(), 1_800_000_000_000
}

func clove(data string) []byte {
	return append([]byte{ratchetGarlicClove, 0, byte(len(data))}, []byte(data)...)
}

func establishRatchet(t testing.TB, a, b *RatchetManager, aPeer, bPeer foundation.Hash, now uint64) foundation.Hash {
	t.Helper()
	bPub := make([]byte, 32)
	copy(bPub, b.private[:]) // public is derived below; this test must not use private material as a public key.
	// Test peers derive the public key through the destination's X25519 scalar.
	curve := ecdh.X25519()
	priv, err := curve.NewPrivateKey(b.private[:])
	if err != nil {
		t.Fatal(err)
	}
	copy(bPub, priv.PublicKey().Bytes())
	ns, err := a.Encrypt(make([]byte, 2048), bPeer, bPub, 4, nil, now)
	if err != nil {
		t.Fatal(err)
	}
	got, err := b.Receive(make([]byte, 2048), make([]byte, 2048), ns, now)
	if err != nil {
		t.Fatal(err)
	}
	if !got.NewSession || got.Candidate == nil || len(got.Payload) != 0 || len(got.Reply) == 0 {
		t.Fatalf("new session result = %#v", got)
	}
	if commit, commitErr := b.CommitNewSession(got.Candidate, got.Peer, now); commitErr != nil || commit != NewSessionInstalled {
		t.Fatalf("new session commit = %v, %v", commit, commitErr)
	}
	if _, err = a.Receive(make([]byte, 2048), make([]byte, 1), got.Reply, now); err != nil {
		t.Fatal(err)
	}
	return got.Peer
}
func TestRatchetUnboundNewSessionDeliversWithoutReplyState(t *testing.T) {
	a, b, _, _, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	payload := clove("raw")
	packet, err := a.EncryptUnbound(make([]byte, 2048), ratchetPublic(t, b), 4, payload, now)
	if err != nil {
		t.Fatal(err)
	}
	result, err := b.Receive(make([]byte, 2048), make([]byte, 2048), packet, now)
	if err != nil {
		t.Fatal(err)
	}
	if !result.NewSession || result.Candidate != nil || len(result.Reply) != 0 || result.Peer != (foundation.Hash{}) || string(result.Payload) != string(payload) {
		t.Fatalf("unbound result = %#v", result)
	}
	if stats := b.Stats(); stats.Sessions != 0 || stats.Pending != 0 {
		t.Fatalf("unbound retained session state = %+v", stats)
	}
}

func TestRatchetBoundNewSessionDoesNotInstallBeforeCommit(t *testing.T) {
	a, b, _, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	packet, err := a.Encrypt(make([]byte, 2048), bPeer, ratchetPublic(t, b), 4, clove("prepared"), now)
	if err != nil {
		t.Fatal(err)
	}
	result, err := b.Receive(make([]byte, 2048), make([]byte, 2048), packet, now)
	if err != nil {
		t.Fatal(err)
	}
	if result.Candidate == nil {
		t.Fatal("bound New Session did not return an admission candidate")
	}
	if stats := b.Stats(); stats.Sessions != 0 || stats.InboundTags != 0 || stats.NewSessions != 1 {
		t.Fatalf("Receive installed candidate state: %+v", stats)
	}
	result.Candidate.Discard()
	result.Candidate.Discard()
	if stats := b.Stats(); stats.Sessions != 0 || stats.InboundTags != 0 {
		t.Fatalf("discarded candidate retained live state: %+v", stats)
	}
}

func TestReplyTagSetKDFMatchesJavaI2P2130Vector(t *testing.T) {
	// Generated by RatchetTagSet from the I2P 2.13.0 release router.jar
	// using i2p.jar SHA-256 1a6f9296fcd07854dffce9c11850c2ebe75a2269aab39e2be869168c0ebc6ef7.
	const javaData = "0665ff1f1ebfe25e4facf84840b0428296e73662ff3b77edfe4904bf7063e3fa"
	const javaNextRoot = "f764b2c8a236502964fde33cd9d81aaf882ba2403f59c916a3e244d9ffb0f6a7"
	javaEntries := []struct {
		tag string
		key string
	}{
		{"2698fd64096e9f0d", "59e67dac8fe352e2956bd84f911efc7b6f1933c05da05360554c88614978ca66"},
		{"8eb1f7070dc0e53d", "f822968404d098d2030a6b93eab2a6ca9c6eac4853a471bc60b82b43011232ae"},
		{"60c4eaee68a6ede1", "e3e860ecd0f17cc31e2b86bfe45320980e8ca183aaaf18b4050584c65697d8a0"},
	}
	var chain [32]byte
	for i := range chain {
		chain[i] = byte(i + 1)
	}
	data := hkdf64(chain[:], nil, "SessionReplyTags")
	if got := hex.EncodeToString(data[:32]); got != javaData {
		t.Fatalf("SessionReplyTags KDF = %s, want Java I2P 2.13.0 %s", got, javaData)
	}
	set, err := newTagSet(0, chain, data[:32], 1)
	if err != nil {
		t.Fatal(err)
	}
	if got := hex.EncodeToString(set.nextRoot[:]); got != javaNextRoot {
		t.Fatalf("next root = %s, want Java I2P 2.13.0 %s", got, javaNextRoot)
	}
	reply := deriveReplyTag(chain)
	if got := hex.EncodeToString(reply[:]); got != javaEntries[0].tag {
		t.Fatalf("reply tag = %s, want Java I2P 2.13.0 %s", got, javaEntries[0].tag)
	}
	for index, want := range javaEntries {
		entry, nextErr := set.nextEntry()
		if nextErr != nil {
			t.Fatal(nextErr)
		}
		if got := hex.EncodeToString(entry.tag[:]); got != want.tag {
			t.Fatalf("tag %d = %s, want Java I2P 2.13.0 %s", index, got, want.tag)
		}
		if got := hex.EncodeToString(entry.key[:]); got != want.key {
			t.Fatalf("key %d = %s, want Java I2P 2.13.0 %s", index, got, want.key)
		}
	}
}

func TestRatchetDHStepMatchesJavaI2P2130Vector(t *testing.T) {
	// Generated by the official I2P 2.13.0 RatchetTagSet and HKDF classes.
	var root, data, shared [32]byte
	for index := range root {
		root[index] = byte(index + 0x01)
		data[index] = byte(index + 0x21)
		shared[index] = byte(index + 0x41)
	}
	initial, err := newTagSet(0, root, data[:], 0)
	if err != nil {
		t.Fatal(err)
	}
	defer releaseTagSet(initial)
	manager := &RatchetManager{config: RatchetConfig{SessionLifetime: defaultSessionLife}}
	next, _, err := manager.prepareRatchetDirectionLocked(&session{outbound: initial}, true, shared[:], 0)
	if err != nil {
		t.Fatal(err)
	}
	defer releaseTagSet(next)
	if got := hex.EncodeToString(next.nextRoot[:]); got != "5b9f9d2d46bec1d6dfd55be052a4f00291a547541c850c83ea1e14ac2db745fd" {
		t.Fatalf("post-DH root differs from Java I2P: %s", got)
	}
	want := []struct{ tag, key string }{
		{"2569ae803872b0fb", "28198055cf8bb04edc906c4bed05d832ca5b96ee5bdf9f71aa5d6a3e9e66697b"},
		{"58212a3e735e815e", "11c9f9fa7997a03766199a65b2b539d6fbbf1936332311c53939da96c36f1a1d"},
		{"1278007fe4f02336", "8ec9804f4320cb4e243f20d463145556424b11af4f69c034b5518e5a85088e7a"},
	}
	for index, entry := range want {
		got, err := next.nextEntry()
		if err != nil {
			t.Fatal(err)
		}
		if hex.EncodeToString(got.tag[:]) != entry.tag || hex.EncodeToString(got.key[:]) != entry.key {
			t.Fatalf("post-DH entry %d differs from Java I2P: tag=%x key=%x", index, got.tag, got.key)
		}
		clear(got.key[:])
	}
}

func TestRatchetExistingSessionUsesNoiseLittleEndianNonce(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	establishRatchet(t, a, b, aPeer, bPeer, now)
	first, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("first"), RatchetOptions{}, now+1)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = b.Receive(make([]byte, 256), nil, first, now+1); err != nil {
		t.Fatal(err)
	}
	second, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("second"), RatchetOptions{}, now+2)
	if err != nil {
		t.Fatal(err)
	}
	var tag [ratchetTagLen]byte
	copy(tag[:], second)
	entry, ok := b.inbound[tag]
	if !ok || entry.n == 0 {
		t.Fatalf("second message tag entry = %#v, found %t", entry, ok)
	}
	var nonce [cryptography.ChaChaNonceSize]byte
	binary.LittleEndian.PutUint64(nonce[4:], uint64(entry.n))
	plain := make([]byte, len(second)-ratchetTagLen-cryptography.ChaChaTagSize)
	if _, err = cryptography.OpenChaCha20Poly1305To(plain, entry.key[:], nonce[:], second[ratchetTagLen:], second[:ratchetTagLen]); err != nil {
		t.Fatal(err)
	}
}

func TestRatchetProductionEncryptAutomaticallyAdvancesDH(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	public := ratchetPublic(t, b)
	var encrypted, received [256]byte
	for index := uint64(1); index <= automaticDHRatchetMessages; index++ {
		packet, err := a.Encrypt(encrypted[:], bPeer, public, 4, nil, now+index)
		if err != nil {
			t.Fatal(err)
		}
		if _, err = b.Receive(received[:], nil, packet, now+index); err != nil {
			t.Fatal(err)
		}
	}
	forward, err := a.Encrypt(encrypted[:], bPeer, public, 4, clove("forward"), now+automaticDHRatchetMessages+1)
	if err != nil {
		t.Fatal(err)
	}
	result, err := b.Receive(received[:], nil, forward, now+automaticDHRatchetMessages+1)
	if err != nil || !result.DHStep {
		t.Fatalf("automatic forward DH = %#v, %v", result, err)
	}
	repeated, err := a.Encrypt(encrypted[:], bPeer, public, 4, clove("repeated"), now+automaticDHRatchetMessages+2)
	if err != nil {
		t.Fatal(err)
	}
	if result, err = b.Receive(received[:], nil, repeated, now+automaticDHRatchetMessages+2); err != nil || !result.DHStep {
		t.Fatalf("idempotent pending DH = %#v, %v", result, err)
	}
	reverse, err := b.Encrypt(encrypted[:], bInboundPeer, ratchetPublic(t, a), 4, clove("reverse"), now+automaticDHRatchetMessages+3)
	if err != nil {
		t.Fatal(err)
	}
	if result, err = a.Receive(received[:], nil, reverse, now+automaticDHRatchetMessages+3); err != nil || !result.DHStep {
		t.Fatalf("automatic reverse DH = %#v, %v", result, err)
	}
}

func TestRatchetProductionEncryptReplacesRestartableSession(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	_ = establishRatchet(t, a, b, aPeer, bPeer, now)
	a.mu.Lock()
	a.sessions[bPeer].outbound.next = 1 << 16
	a.mu.Unlock()
	restartNow := now + newSessionRestartAge + 1
	packet, err := a.Encrypt(make([]byte, 2048), bPeer, ratchetPublic(t, b), 4, clove("replacement"), restartNow)
	if err != nil {
		t.Fatal(err)
	}
	result, err := b.Receive(make([]byte, 2048), make([]byte, 2048), packet, restartNow)
	if err != nil || !result.NewSession || result.Candidate == nil {
		t.Fatalf("replacement new session = %#v, %v", result, err)
	}
	if commit, commitErr := b.CommitNewSession(result.Candidate, result.Peer, restartNow); commitErr != nil || commit != NewSessionReplaced {
		t.Fatalf("replacement commit = %v, %v", commit, commitErr)
	}
}

func ratchetPublic(t testing.TB, manager *RatchetManager) []byte {
	t.Helper()
	private, err := ecdh.X25519().NewPrivateKey(manager.private[:])
	if err != nil {
		t.Fatal(err)
	}
	return private.PublicKey().Bytes()
}

func TestRatchetNewExistingReplayAndAck(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	packet, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("hello"), RatchetOptions{ACKRequest: true}, now+1)
	if err != nil {
		t.Fatal(err)
	}
	result, err := b.Receive(make([]byte, 256), make([]byte, 1), packet, now+1)
	if err != nil {
		t.Fatal(err)
	}
	if string(result.Payload[:len(clove("hello"))]) != string(clove("hello")) || len(result.ACKRequests) != 1 {
		t.Fatalf("existing result = %#v", result)
	}
	if _, err := b.Receive(make([]byte, 256), make([]byte, 1), packet, now+1); err == nil {
		t.Fatal("replayed existing was accepted")
	}
	ack, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{ACKs: result.ACKRequests}, now+2)
	if err != nil {
		t.Fatal(err)
	}
	ackResult, err := a.Receive(make([]byte, 256), make([]byte, 1), ack, now+2)
	if err != nil {
		t.Fatal(err)
	}
	if len(ackResult.ACKs) != 1 || ackResult.ACKs[0] != result.ACKRequests[0] {
		t.Fatalf("ack result = %#v", ackResult)
	}
}

func TestRatchetActivityExtendsIdleLifetime(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	for range 4 {
		now += defaultSessionLife / 2
		forward, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("PING"), RatchetOptions{}, now)
		if err != nil {
			t.Fatalf("active session send at %d: %v", now, err)
		}
		if got, err := b.Receive(make([]byte, 256), nil, forward, now); err != nil || string(got.Payload) != string(clove("PING")) {
			t.Fatalf("active session receive at %d: payload=%x error=%v", now, got.Payload, err)
		}
		reverse, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, clove("PONG"), RatchetOptions{}, now)
		if err != nil {
			t.Fatal(err)
		}
		if got, err := a.Receive(make([]byte, 256), nil, reverse, now); err != nil || string(got.Payload) != string(clove("PONG")) {
			t.Fatalf("active reply at %d: payload=%x error=%v", now, got.Payload, err)
		}
	}
	if _, err := a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{}, now+defaultSessionLife+1); !errors.Is(err, ErrRatchetNoSession) {
		t.Fatalf("idle session error = %v, want ErrRatchetNoSession", err)
	}
}

func TestRatchetUnauthenticatedTrafficDoesNotExtendIdleLifetime(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	establishRatchet(t, a, b, aPeer, bPeer, now)
	invalid, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("invalid"), RatchetOptions{}, now+defaultSessionLife-1)
	if err != nil {
		t.Fatal(err)
	}
	invalid[len(invalid)-1] ^= 1
	if _, err := b.Receive(make([]byte, 256), nil, invalid, now+defaultSessionLife-1); !errors.Is(err, ErrRatchet) {
		t.Fatalf("tampered packet error = %v, want ErrRatchet", err)
	}
	valid, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("late"), RatchetOptions{}, now+defaultSessionLife-1)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := b.Receive(make([]byte, 256), nil, valid, now+defaultSessionLife+1); err == nil {
		t.Fatal("tampered traffic kept idle receive keys alive")
	}
}

func TestRatchetDHTransitionAndExpiry(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	forward, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("forward"), RatchetOptions{RequestDH: true}, now+1)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = b.Receive(make([]byte, 256), make([]byte, 1), forward, now+1); err != nil {
		t.Fatal(err)
	}
	reverse, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, clove("reverse"), RatchetOptions{}, now+2)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = a.Receive(make([]byte, 256), make([]byte, 1), reverse, now+2); err != nil {
		t.Fatal(err)
	}
	after, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("after"), RatchetOptions{}, now+3)
	if err != nil {
		t.Fatal(err)
	}
	if got, err := b.Receive(make([]byte, 256), make([]byte, 1), after, now+3); err != nil || string(got.Payload) != string(clove("after")) {
		t.Fatalf("post-DH = %#v, %v", got, err)
	}
	if _, err = a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{}, now+3+defaultSessionLife+1); !errors.Is(err, ErrRatchetNoSession) {
		t.Fatalf("expired session = %v", err)
	}
}

func TestRatchetReleasesSupersededDHPrivateKeys(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	var previous *cryptography.X25519PrivateKey
	for step := range 2 {
		forward, err := a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{RequestDH: true}, now)
		if err != nil {
			t.Fatal(err)
		}
		if step == 1 {
			var public [32]byte
			if err := previous.PublicKey(&public); !errors.Is(err, cryptography.ErrSensitiveReleased) {
				t.Fatalf("superseded DH key remains usable: %v", err)
			}
		}
		previous = a.sessions[bPeer].forwardDH.localKey
		if _, err := b.Receive(make([]byte, 256), nil, forward, now); err != nil {
			t.Fatal(err)
		}
		reverse, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{}, now)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := a.Receive(make([]byte, 256), nil, reverse, now); err != nil {
			t.Fatal(err)
		}
	}
	reverseKey := b.sessions[bInboundPeer].reverseDH.localKey
	a.ReleaseSensitive()
	b.ReleaseSensitive()
	for _, key := range []*cryptography.X25519PrivateKey{previous, reverseKey} {
		var public [32]byte
		if err := key.PublicKey(&public); !errors.Is(err, cryptography.ErrSensitiveReleased) {
			t.Fatalf("closed ratchet retained a usable DH key: %v", err)
		}
	}
}

func TestRatchetAcceptsDelayedForwardKeyWithoutAdvancingAgain(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)

	forward, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("forward"), RatchetOptions{RequestDH: true}, now+1)
	if err != nil {
		t.Fatal(err)
	}
	delayed, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("delayed"), RatchetOptions{}, now+2)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = b.Receive(make([]byte, 256), make([]byte, 1), forward, now+1); err != nil {
		t.Fatal(err)
	}
	reverse, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, clove("reverse"), RatchetOptions{}, now+3)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = a.Receive(make([]byte, 256), make([]byte, 1), reverse, now+3); err != nil {
		t.Fatal(err)
	}
	if got, err := b.Receive(make([]byte, 256), nil, delayed, now+4); err != nil || string(got.Payload[:len(clove("delayed"))]) != string(clove("delayed")) {
		t.Fatalf("delayed repeated NextKey = %#v, %v", got, err)
	}
	after, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("after-stale"), RatchetOptions{}, now+5)
	if err != nil {
		t.Fatal(err)
	}
	if got, receiveErr := b.Receive(make([]byte, 256), make([]byte, 1), after, now+5); receiveErr != nil || string(got.Payload) != string(clove("after-stale")) {
		t.Fatalf("session after stale NextKey = %#v, %v", got, receiveErr)
	}
}

func TestRatchetAcceptsRepeatedReverseKeyUntilNewTagReceived(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	forward, err := a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{RequestDH: true}, now+1)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = b.Receive(make([]byte, 256), nil, forward, now+1); err != nil {
		t.Fatal(err)
	}
	for range 2 {
		reverse, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{}, now+2)
		if err != nil {
			t.Fatal(err)
		}
		got, err := a.Receive(make([]byte, 256), nil, reverse, now+2)
		if err != nil {
			t.Fatal(err)
		}
		requireNextKeyHeaders(t, got.Payload, [3]byte{3, 0, 0})
	}
	after, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("new tagset"), RatchetOptions{ACKRequest: true}, now+3)
	if err != nil {
		t.Fatal(err)
	}
	got, err := b.Receive(make([]byte, 256), nil, after, now+3)
	if err != nil || len(got.ACKRequests) != 1 || got.ACKRequests[0] != (ACK{1, 0}) {
		t.Fatalf("new tagset after repeated reverse key = %#v, %v", got, err)
	}
	ack, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{ACKs: got.ACKRequests}, now+4)
	if err != nil {
		t.Fatal(err)
	}
	got, err = a.Receive(make([]byte, 256), nil, ack, now+4)
	if err != nil {
		t.Fatal(err)
	}
	requireNextKeyHeaders(t, got.Payload)
}

func TestRatchetDelayedReverseKeyDoesNotInterruptLaterExchange(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	var delayed []byte
	for step := range 3 {
		forward, err := a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{RequestDH: true}, now)
		if err != nil {
			t.Fatal(err)
		}
		if step == 2 {
			got, err := a.Receive(make([]byte, 256), nil, delayed, now)
			if err != nil || len(got.Payload) < len(clove("delayed reverse")) || string(got.Payload[:len(clove("delayed reverse"))]) != string(clove("delayed reverse")) {
				t.Fatalf("old reverse key interrupted new exchange: %#v, %v", got, err)
			}
		}
		if _, err = b.Receive(make([]byte, 256), nil, forward, now); err != nil {
			t.Fatal(err)
		}
		reverse, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{}, now)
		if err != nil {
			t.Fatal(err)
		}
		if _, err = a.Receive(make([]byte, 256), nil, reverse, now); err != nil {
			t.Fatal(err)
		}
		if step == 0 {
			delayed, err = b.EncryptExisting(make([]byte, 256), bInboundPeer, clove("delayed reverse"), RatchetOptions{}, now)
			if err != nil {
				t.Fatal(err)
			}
		}
	}
	after, err := a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{ACKRequest: true}, now)
	if err != nil {
		t.Fatal(err)
	}
	got, err := b.Receive(make([]byte, 256), nil, after, now)
	if err != nil || len(got.ACKRequests) != 1 || got.ACKRequests[0] != (ACK{3, 0}) {
		t.Fatalf("later exchange after stale reverse = %#v, %v", got, err)
	}
}
func TestRatchetUsesFinalTagSetBeforeRequiringNewSession(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	forward, err := a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{RequestDH: true}, now)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = b.Receive(make([]byte, 256), nil, forward, now); err != nil {
		t.Fatal(err)
	}
	reverse, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{}, now)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = a.Receive(make([]byte, 256), nil, reverse, now); err != nil {
		t.Fatal(err)
	}
	// Retain matching keys/chains while advancing to the last key-ID boundary.
	a.sessions[bPeer].outbound.id = 65534
	a.sessions[bPeer].forwardDH.localKeyID = 32767
	a.sessions[bPeer].forwardDH.remoteKeyID = 32766
	b.sessions[bInboundPeer].inbound.id = 65534
	b.sessions[bInboundPeer].reverseDH.remoteKeyID = 32767
	b.sessions[bInboundPeer].reverseDH.localKeyID = 32766
	forward, err = a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{RequestDH: true}, now+1)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = b.Receive(make([]byte, 256), nil, forward, now+1); err != nil {
		t.Fatal(err)
	}
	reverse, err = b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{}, now+2)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = a.Receive(make([]byte, 256), nil, reverse, now+2); err != nil {
		t.Fatal(err)
	}
	last, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("final tagset"), RatchetOptions{ACKRequest: true}, now+3)
	if err != nil {
		t.Fatal(err)
	}
	got, err := b.Receive(make([]byte, 256), nil, last, now+3)
	if err != nil || len(got.ACKRequests) != 1 || got.ACKRequests[0] != (ACK{65535, 0}) {
		t.Fatalf("last tagset delivery = %#v, %v", got, err)
	}
	if _, err = a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{RequestDH: true}, now+4); !errors.Is(err, ErrRatchetTagExhausted) {
		t.Fatalf("rotation beyond tagset 65535 = %v", err)
	}
}

func TestRatchetForwardNextKeyCapacityFailureIsAtomic(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	forward, err := a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{RequestDH: true}, now+1)
	if err != nil {
		t.Fatal(err)
	}
	b.mu.Lock()
	b.config.MaxInboundTags = len(b.inbound)
	b.mu.Unlock()
	if _, err = b.Receive(make([]byte, 256), make([]byte, 1), forward, now+1); !errors.Is(err, ErrRatchetTagExhausted) {
		t.Fatalf("capacity-saturated forward NextKey = %v", err)
	}
	if _, err = b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{}, now+2); !errors.Is(err, ErrRatchetNoSession) {
		t.Fatalf("capacity-failed ratchet remained usable: %v", err)
	}
}

func TestRatchetReverseKeyDoesNotConsumeInboundCapacity(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	forward, err := a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{RequestDH: true}, now+1)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = b.Receive(make([]byte, 256), make([]byte, 1), forward, now+1); err != nil {
		t.Fatal(err)
	}
	reverse, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{}, now+2)
	if err != nil {
		t.Fatal(err)
	}
	a.mu.Lock()
	a.config.MaxInboundTags = len(a.inbound)
	a.mu.Unlock()
	if _, err = a.Receive(make([]byte, 256), nil, reverse, now+2); err != nil {
		t.Fatalf("reverse NextKey at inbound capacity: %v", err)
	}
	after, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("new outbound"), RatchetOptions{ACKRequest: true}, now+3)
	if err != nil {
		t.Fatal(err)
	}
	got, err := b.Receive(make([]byte, 256), nil, after, now+3)
	if err != nil || len(got.ACKRequests) != 1 || got.ACKRequests[0] != (ACK{1, 0}) {
		t.Fatalf("new outbound tagset delivery = %#v, %v", got, err)
	}
}

func TestRatchetNextKeySequenceMatchesJavaDirections(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	steps := []struct{ forward, reverse [3]byte }{
		{[3]byte{5, 0, 0}, [3]byte{3, 0, 0}},
		{[3]byte{1, 0, 1}, [3]byte{2, 0, 0}},
		{[3]byte{4, 0, 1}, [3]byte{3, 0, 1}},
		{[3]byte{1, 0, 2}, [3]byte{2, 0, 1}},
	}
	for index, step := range steps {
		forward, err := a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{RequestDH: true}, now)
		if err != nil {
			t.Fatal(err)
		}
		got, err := b.Receive(make([]byte, 256), nil, forward, now)
		if err != nil {
			t.Fatal(err)
		}
		requireNextKeyHeaders(t, got.Payload, step.forward)
		reverse, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{}, now)
		if err != nil {
			t.Fatal(err)
		}
		got, err = a.Receive(make([]byte, 256), nil, reverse, now)
		if err != nil {
			t.Fatal(err)
		}
		requireNextKeyHeaders(t, got.Payload, step.reverse)
		after, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("forward data"), RatchetOptions{ACKRequest: true}, now)
		if err != nil {
			t.Fatal(err)
		}
		got, err = b.Receive(make([]byte, 256), nil, after, now)
		if err != nil || len(got.ACKRequests) != 1 || got.ACKRequests[0] != (ACK{uint16(index + 1), 0}) {
			t.Fatalf("tagset %d delivery = %#v, %v", index+1, got, err)
		}
		back, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, clove("reverse data"), RatchetOptions{ACKRequest: true}, now)
		if err != nil {
			t.Fatal(err)
		}
		got, err = a.Receive(make([]byte, 256), nil, back, now)
		if err != nil || len(got.ACKRequests) != 1 || got.ACKRequests[0].TagSet != 0 {
			t.Fatalf("opposite direction changed tagset: %#v, %v", got, err)
		}
		requireNextKeyHeaders(t, got.Payload)
	}
}

func TestRatchetSimultaneousDirectionalKeyExchanges(t *testing.T) {
	a, b, aPeer, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	aForward, err := a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{RequestDH: true}, now)
	if err != nil {
		t.Fatal(err)
	}
	bForward, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{RequestDH: true}, now)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = a.Receive(make([]byte, 256), nil, bForward, now); err != nil {
		t.Fatal(err)
	}
	if _, err = b.Receive(make([]byte, 256), nil, aForward, now); err != nil {
		t.Fatal(err)
	}
	aReverse, err := a.EncryptExisting(make([]byte, 256), bPeer, nil, RatchetOptions{}, now)
	if err != nil {
		t.Fatal(err)
	}
	got, err := b.Receive(make([]byte, 256), nil, aReverse, now)
	if err != nil {
		t.Fatal(err)
	}
	requireNextKeyHeaders(t, got.Payload, [3]byte{5, 0, 0}, [3]byte{3, 0, 0})
	bReverse, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, nil, RatchetOptions{}, now)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = a.Receive(make([]byte, 256), nil, bReverse, now); err != nil {
		t.Fatal(err)
	}
	after, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("both directions advanced"), RatchetOptions{ACKRequest: true}, now)
	if err != nil {
		t.Fatal(err)
	}
	got, err = b.Receive(make([]byte, 256), nil, after, now)
	if err != nil || len(got.ACKRequests) != 1 || got.ACKRequests[0].TagSet != 1 {
		t.Fatalf("forward after simultaneous exchange = %#v, %v", got, err)
	}
	after, err = b.EncryptExisting(make([]byte, 256), bInboundPeer, clove("both directions advanced"), RatchetOptions{ACKRequest: true}, now)
	if err != nil {
		t.Fatal(err)
	}
	got, err = a.Receive(make([]byte, 256), nil, after, now)
	if err != nil || len(got.ACKRequests) != 1 || got.ACKRequests[0].TagSet != 1 {
		t.Fatalf("reverse after simultaneous exchange = %#v, %v", got, err)
	}
}

func requireNextKeyHeaders(t testing.TB, payload []byte, want ...[3]byte) {
	t.Helper()
	var got [][3]byte
	for len(payload) >= 3 {
		kind, size := payload[0], int(binary.BigEndian.Uint16(payload[1:3]))
		payload = payload[3:]
		if size > len(payload) {
			t.Fatal("truncated authenticated payload")
		}
		if kind == ratchetNextKey {
			if size != 3 && size != 35 {
				t.Fatalf("NextKey size = %d", size)
			}
			got = append(got, [3]byte(payload[:3]))
		}
		payload = payload[size:]
	}
	if len(got) != len(want) {
		t.Fatalf("NextKey headers = %x, want %x", got, want)
	}
	for index := range want {
		if got[index] != want[index] {
			t.Fatalf("NextKey headers = %x, want %x", got, want)
		}
	}
}

func TestRatchetMetricsRecordAuthenticatedTransitions(t *testing.T) {
	metrics := observability.NewRegistry()
	a, b, aPeer, bPeer, now := ratchetPairWithMetrics(t, metrics)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	bInboundPeer := establishRatchet(t, a, b, aPeer, bPeer, now)
	forward, err := a.EncryptExisting(make([]byte, 256), bPeer, clove("forward"), RatchetOptions{RequestDH: true}, now+1)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = b.Receive(make([]byte, 256), make([]byte, 1), forward, now+1); err != nil {
		t.Fatal(err)
	}
	reverse, err := b.EncryptExisting(make([]byte, 256), bInboundPeer, clove("reverse"), RatchetOptions{}, now+2)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = a.Receive(make([]byte, 256), make([]byte, 1), reverse, now+2); err != nil {
		t.Fatal(err)
	}
	got := metrics.Snapshot().Garlic
	ratchetMetricsRecordAuthenticatedTransitionsRejected := got.NewSessionSent != 1 || got.NewSessionReceived != 2 ||
		got.ExistingSessionSent != 2 || got.ExistingSessionReceived != 2 ||
		got.DHStepsSent != 2
	if !ratchetMetricsRecordAuthenticatedTransitionsRejected {
		ratchetMetricsRecordAuthenticatedTransitionsRejected = got.DHStepsReceived != 2
	}
	if ratchetMetricsRecordAuthenticatedTransitionsRejected {
		t.Fatalf("ratchet metrics = %+v", got)
	}
}

func BenchmarkRatchetExistingWithScratch(b *testing.B) {
	a, receiver, aPeer, bPeer, now := ratchetPair(b)
	defer a.ReleaseSensitive()
	defer receiver.ReleaseSensitive()
	receiverPeer := establishRatchet(b, a, receiver, aPeer, bPeer, now)
	payload := []byte{ratchetGarlicClove, 0, 1, 9}
	var encrypted, plain, received, reply [256]byte
	for index := uint64(1); index <= 64; index++ {
		packet, err := a.EncryptExistingWithScratch(encrypted[:], plain[:], bPeer, payload, RatchetOptions{}, now+index)
		if err != nil {
			b.Fatal(err)
		}
		if _, err = receiver.Receive(received[:], reply[:], packet, now+index); err != nil {
			b.Fatal(err)
		}
	}
	state := ratchetBenchmarkState{
		sender:       a,
		receiver:     receiver,
		senderPeer:   bPeer,
		receiverPeer: receiverPeer,
		payload:      payload,
		encrypted:    &encrypted,
		plain:        &plain,
		received:     &received,
		reply:        &reply,
		now:          now,
		offset:       65,
	}
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		state.step(b)
	}
}

type ratchetBenchmarkState struct {
	sender       *RatchetManager
	receiver     *RatchetManager
	senderPeer   foundation.Hash
	receiverPeer foundation.Hash
	payload      []byte
	encrypted    *[256]byte
	plain        *[256]byte
	received     *[256]byte
	reply        *[256]byte
	now          uint64
	offset       uint64
}

func (state *ratchetBenchmarkState) step(b *testing.B) {
	if state.offset%4000 == 0 {
		b.StopTimer()
		state.rekey(b)
		b.StartTimer()
	}
	packet, err := state.sender.EncryptExistingWithScratch(state.encrypted[:], state.plain[:], state.senderPeer, state.payload, RatchetOptions{}, state.now+state.offset)
	if err == nil {
		_, err = state.receiver.Receive(state.received[:], state.reply[:], packet, state.now+state.offset)
	}
	if err != nil {
		b.Fatal(err)
	}
	state.offset++
}

func (state *ratchetBenchmarkState) rekey(b *testing.B) {
	forward, err := state.sender.EncryptExistingWithScratch(state.encrypted[:], state.plain[:], state.senderPeer, nil, RatchetOptions{RequestDH: true}, state.now+state.offset)
	if err == nil {
		_, err = state.receiver.Receive(state.received[:], state.reply[:], forward, state.now+state.offset)
	}
	if err == nil {
		reverse, reverseErr := state.receiver.EncryptExistingWithScratch(state.encrypted[:], state.plain[:], state.receiverPeer, nil, RatchetOptions{}, state.now+state.offset)
		err = reverseErr
		if err == nil {
			_, err = state.sender.Receive(state.received[:], state.reply[:], reverse, state.now+state.offset)
		}
	}
	if err != nil {
		b.Fatal(err)
	}
}

func TestRatchetRejectsNewSessionReplayAndClockSkew(t *testing.T) {
	a, b, _, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	curve := ecdh.X25519()
	private, err := curve.NewPrivateKey(b.private[:])
	if err != nil {
		t.Fatal(err)
	}
	ns, err := a.Encrypt(make([]byte, 2048), bPeer, private.PublicKey().Bytes(), 4, nil, now)
	if err != nil {
		t.Fatal(err)
	}
	result, err := b.Receive(make([]byte, 2048), make([]byte, 2048), ns, now)
	if err != nil {
		t.Fatal(err)
	}
	if result.Candidate == nil {
		t.Fatal("authenticated New Session did not return a candidate")
	}
	defer result.Candidate.Discard()
	if _, err = b.Receive(make([]byte, 2048), make([]byte, 2048), ns, now); !errors.Is(err, ErrRatchetReplay) {
		t.Fatalf("new-session replay = %v", err)
	}
	if _, err = b.Receive(make([]byte, 2048), make([]byte, 2048), ns, now+301_000); !errors.Is(err, ErrRatchet) && !errors.Is(err, ErrRatchetReplay) && !errors.Is(err, ErrRatchetExpired) {
		t.Fatalf("expired datetime = %v", err)
	}
}

func TestRatchetRejectsRemovedCryptoType5(t *testing.T) {
	local, err := foundation.GenerateLocalDestination()
	if err != nil {
		t.Fatal(err)
	}
	defer local.ReleaseSensitive()
	if manager, err := NewRatchetManager(local, RatchetConfig{CryptoTypes: []uint16{5}}); err == nil || manager != nil {
		t.Fatalf("NewRatchetManager(type 5) = %#v, %v", manager, err)
	}
	manager, err := NewRatchetManager(local, RatchetConfig{})
	if err != nil {
		t.Fatal(err)
	}
	defer manager.ReleaseSensitive()
	if _, err = manager.Encrypt(make([]byte, 4096), foundation.Sum([]byte("peer")), make([]byte, 32), 5, []byte{1, 2, 3}, 1_700_000_000_000); !errors.Is(err, ErrRatchet) {
		t.Fatalf("Encrypt(type 5) = %v", err)
	}
}
func TestRatchetDefaultReceiverNegotiatesEveryProductionCryptoType(t *testing.T) {
	for _, cryptoType := range []uint16{7, 6, 4} {
		t.Run(string(rune('0'+cryptoType)), func(t *testing.T) {
			a, b, _, bPeer, now := ratchetPair(t)
			defer a.ReleaseSensitive()
			defer b.ReleaseSensitive()
			private, err := ecdh.X25519().NewPrivateKey(b.private[:])
			if err != nil {
				t.Fatal(err)
			}
			ns, err := a.Encrypt(make([]byte, 4096), bPeer, private.PublicKey().Bytes(), cryptoType, clove("hybrid"), now)
			if err != nil {
				t.Fatal(err)
			}
			result, err := b.Receive(make([]byte, 4096), make([]byte, 4096), ns, now)
			if err != nil {
				t.Fatal(err)
			}
			if !result.NewSession || result.Candidate == nil || string(result.Payload) != string(clove("hybrid")) || len(result.Reply) == 0 {
				t.Fatalf("crypto type %d result = %#v", cryptoType, result)
			}
			if commit, commitErr := b.CommitNewSession(result.Candidate, result.Peer, now); commitErr != nil || commit != NewSessionInstalled {
				t.Fatalf("crypto type %d commit = %v, %v", cryptoType, commit, commitErr)
			}
			if _, err = a.Receive(make([]byte, 4096), nil, result.Reply, now); err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestRatchetNewSessionCommitIsAtomicAfterReplyFailure(t *testing.T) {
	a, b, _, bPeer, now := ratchetPair(t)
	defer a.ReleaseSensitive()
	defer b.ReleaseSensitive()
	private, err := ecdh.X25519().NewPrivateKey(b.private[:])
	if err != nil {
		t.Fatal(err)
	}
	ns, err := a.Encrypt(make([]byte, 4096), bPeer, private.PublicKey().Bytes(), 7, nil, now)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = b.Receive(make([]byte, 4096), make([]byte, 1), ns, now); err == nil {
		t.Fatal("short reply buffer accepted")
	}
	if stats := b.Stats(); stats.Sessions != 0 || stats.NewSessions != 0 {
		t.Fatalf("failed transition committed state: %+v", stats)
	}
	result, err := b.Receive(make([]byte, 4096), make([]byte, 4096), ns, now)
	if err != nil {
		t.Fatalf("retry after terminal failure = %v", err)
	}
	result.Candidate.Discard()
}
